# Generated by Django 5.2.3 on 2025-06-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='county',
        ),
    ]
