# Generated by Django 5.2.3 on 2025-06-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Website', '0002_rename_state_record_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='postcode',
        ),
    ]
