# Generated by Django 6.0.3 on 2026-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Website', '0003_rename_zipcode_record_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
